<a href="https://colab.research.google.com/github/mjbooo/Pr4AI/blob/main/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#210308
import numpy as np
#numpy= matlab for python (especially LA task)

In [ ]:
def print_obj(obj, name):
    print("%s:\n%s\n" % (name, obj))
    
def check_each(a, b):
    return (a == b).astype('bool')

def check_mean(a, b):
    return np.mean(a == b).astype('bool')

#just to make tutorial easier

### Scalars, Vectors, Matrices

In [ ]:
a = np.array(1.)
b = np.array([1., 2., 3.])
c = np.array([[1., 2., 3.], [4., 5., 6.]])

In [ ]:
print(1., 1)
#difference b.w 1. and 1

1.0 1


In [ ]:
print_obj(a, "a")
print_obj(b, "b")
print_obj(c, "c")

a:
1.0

b:
[1. 2. 3.]

c:
[[1. 2. 3.]
 [4. 5. 6.]]



In [ ]:
print_obj(a.ndim, "a.ndim") #scalar
print_obj(b.ndim, "b.ndim")
print_obj(c.ndim, "c.ndim")
#ndim= # of dimensionality, axes

a.ndim:
0

0
b.ndim:
1

c.ndim:
2



In [ ]:
print_obj(a.shape, "a.shape")
print_obj(b.shape, "b.shape")
print_obj(c.shape, "c.shape")
print_obj(c.shape[0], "c.shape") #first elem of shape obj= # of rows

a.shape:
()

b.shape:
(3,)

c.shape:
(2, 3)

c.shape:
2



### Tensors (N-dimensional array s.t N>=3)

In [ ]:
d = np.array([[[1., 2., 3.], [4., 5., 6.]], [[7., 8., 9.], [10., 11., 12.]]])
d[0]
e = np.array([[[[1., 2., 3.], [1., 2., 3.]], [[4., 5., 6.], [4., 5., 6.]]],
              [[[7., 8., 9.], [7., 8., 9.]], [[10., 11., 12.], [10., 11., 12.]]]])

In [ ]:
print_obj(d, "d")
print_obj(d.ndim, "d.ndim")
print_obj(d.shape, "d.shape")

print('order: outer bracket -> inner bracket')
print('d[0]:\n',d[0],'\nd[1]:\n',d[1])
print('d[0][0]:\n',d[0][0],'\nd[0][1]:\n',d[0][1])
print('d[0][0][0]:\n',d[0][0][0],'\nd[0][0][1]:\n',d[0][0][1])


print_obj(e, "e")
print_obj(e.ndim, "e.ndim")
print_obj(e.shape, "e.shape")

d:
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]

d.ndim:
3

d.shape:
(2, 2, 3)

order: outer bracket -> inner bracket
d[0]:
 [[1. 2. 3.]
 [4. 5. 6.]] 
d[1]:
 [[ 7.  8.  9.]
 [10. 11. 12.]]
d[0][0]:
 [1. 2. 3.] 
d[0][1]:
 [4. 5. 6.]
d[0][0][0]:
 1.0 
d[0][0][1]:
 2.0
e:
[[[[ 1.  2.  3.]
   [ 1.  2.  3.]]

  [[ 4.  5.  6.]
   [ 4.  5.  6.]]]


 [[[ 7.  8.  9.]
   [ 7.  8.  9.]]

  [[10. 11. 12.]
   [10. 11. 12.]]]]

e.ndim:
4

e.shape:
(2, 2, 2, 3)



In [ ]:
# Quiz: What is the shape of [[[1], [2], [3]], [[4], [5], [6]]]?
# A:2,3,1
quiz = np.array([[[2], [2], [3]], [[4], [5], [6]]])
print(quiz.shape)
print(type(quiz))

# proper tensor dtype=<class 'numpy.ndarray'>

(2, 3, 1)
<class 'numpy.ndarray'>


### Defining Numpy arrays

In [ ]:
a = np.ones((10,3))
# input dtype= tuple
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a = np.zeros((2, 5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
a = np.full((2,5), 5)
a

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [ ]:
a = np.random.random((2, 3, 4))
# np.random.random(t): U[0,1]
a

array([[[0.66221533, 0.54693442, 0.57119273, 0.78188577],
        [0.21963625, 0.07344145, 0.82794823, 0.89668045],
        [0.22549842, 0.03143434, 0.08043295, 0.11500477]],

       [[0.13357219, 0.05765124, 0.45542329, 0.77863817],
        [0.88591946, 0.78839692, 0.32172106, 0.3016293 ],
        [0.53123377, 0.70581554, 0.59653549, 0.35172642]]])

In [ ]:
a = np.arange(10) # starting from 0
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.arange(10).astype(float)
a
a = np.arange(10).astype(bool)
a

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
# important API
a = np.arange(10).reshape((5,2))
a

In [ ]:
# Quiz: Create a 4-by-3-by-2 tensor filled with 0.0 to 23.0
a= np.arange(24).astype(float).reshape((4,3,2))
a

<class 'int'>


array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.]],

       [[ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]],

       [[12., 13.],
        [14., 15.],
        [16., 17.]],

       [[18., 19.],
        [20., 21.],
        [22., 23.]]])

### Indexing & Slicing

In [ ]:
# Indexing and slicing a vector
a = np.arange(10)
print_obj(a, "a")
'''
print_obj(a[0], "a[0]")
print_obj(a[1], "a[1]")
print_obj(a[-1], "a[-1]")
print_obj(a[-3], "a[-3]")
'''

# starting index(included):ending index(not included)
# blank means zero
'''
print_obj(a[0:10], "a[0:10]")
print_obj(a[0:], "a[0:]")
print_obj(a[:10], "a[:10]")
print_obj(a[:], "a[:]")
'''

'''
print_obj(a[7:], "a[7:]")
print_obj(a[:5], "a[:5]")
print_obj(a[2:5], "a[2:5]")

# Quiz: What is a[-4:]?
# A: 6, 7, 8, 9
print(a[-4:])

# Quiz: What is a[:-8]?
# A: 0, 1
print(a[:-8])
'''


print_obj(a[0:10:2], "a[0:10:2]")
print_obj(a[0:10:3], "a[0:10:3]")
print_obj(a[2:6:3], "a[2:6:3]")

print_obj(a[::-1], "a[::-1]") # s(blank=first idx):e(blank=last idx)
print_obj(a[8:5:-1], "a[8:5:-1]")
print_obj(a[8:5], "a[8:5]") #blank= 1


# Quiz: Create [9, 6, 3] using a.
print(a[-1:0:-3]) #M1
print(a[9:2:-3]) #M2

a:
[0 1 2 3 4 5 6 7 8 9]

a[0:10:2]:
[0 2 4 6 8]

a[0:10:3]:
[0 3 6 9]

a[2:6:3]:
[2 5]

a[::-1]:
[9 8 7 6 5 4 3 2 1 0]

a[8:5:-1]:
[8 7 6]

a[8:5]:
[]

[9 6 3]
[9 6 3]


In [ ]:
# Indexing a matrix
a = np.arange(9).reshape((3,3))
print_obj(a, "a")
print_obj(a[0][0], "a[0][0]")
print_obj(a[0,0], "a[0,0]")
print_obj(a[1,1], "a[1,1]")

# Quiz: How to access the last row?
print(a[-1])
print(a[-1][:])
print(a[-1,:])

# Quiz: How to access the second column?
print(a[:,1])

# Quiz: How to create [8, 5] using a?
print(a[-1:0:-1][:,2])
print(a[-1:0:-1,2])
print(a[2:0:-1, 2])

a:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

a[0][0]:
0

a[0,0]:
0

a[1,1]:
4

[6 7 8]
[6 7 8]
[6 7 8]
[1 4 7]
[8 5]
[8 5]
[8 5]


In [ ]:
# Indexing and slicing a 3D tensor
a = np.arange(4*3*2).reshape((4, 3, 2))
print_obj(a, "a")
print_obj(a[2, 1, 0], "a[2, 1, 0]")

# Quiz: What would be a[0]?
# A: first mat

# Quiz: What would be a[0, 1]?
# A: 2nd row of first mat

# Quiz: Create [[0, 2, 4], [6, 8, 10]]
a[:2,:,0] # first 2 mat, all rows, 1st col

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

a[2, 1, 0]:
14



array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [ ]:
# Conditional indexing (any condition like >, <. = ...)
a = np.arange(3*2).reshape((3,2))
print_obj(a, "a")

idx = a % 2 == 0
print_obj(idx, "idx")
a[idx]

# Quiz: How would you create [3, 4, 5] using a?
a[a>2]

a:
[[0 1]
 [2 3]
 [4 5]]

idx:
[[ True False]
 [ True False]
 [ True False]]



array([3, 4, 5])

In [ ]:
# Taking specific elements from a vector
a = np.arange(10)
idx = [0, 2, 3]
print_obj(a[idx], "a[idx]")

a[idx]:
[0 2 3]



In [ ]:
# Taking specific elements from a tensor
a = np.arange(24).reshape((6,4))
print_obj(a, "a")

print_obj(a[:,[0, 2, 3]], "a[idx]")
print_obj(a[[0, 2, 3], :], "a[idx]")



idx = ((0,0,1,5),(1,2,0,3)) # parallel matching
print_obj(a[idx], "tuple indexing")

idx = np.array([[0,0,1,5],[1,2,0,3]]) 
print_obj(a[idx], "ndarray indexing") #mat in mat = tensor

idx = np.array([[[0,1],[0,1]]]) 
print_obj(a[idx], "ndarray indexing")

a:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

a[idx]:
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]
 [16 18 19]
 [20 22 23]]

a[idx]:
[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]

tuple indexing:
[ 1  2  4 23]

ndarray indexing:
[[[ 0  1  2  3]
  [ 0  1  2  3]
  [ 4  5  6  7]
  [20 21 22 23]]

 [[ 4  5  6  7]
  [ 8  9 10 11]
  [ 0  1  2  3]
  [12 13 14 15]]]

ndarray indexing:
[[[[0 1 2 3]
   [4 5 6 7]]

  [[0 1 2 3]
   [4 5 6 7]]]]



### Math Operations

In [ ]:
# Basic operations
a = np.arange(6).reshape((3, 2))
b = np.ones((3, 2))
print_obj(a, "a")
print_obj(b, "b")

# +, -, *, /
print_obj(a+b, "a+b")
print_obj(a-b, "a-b")
print_obj(a*b, "a*b")
print_obj(a/b, "a/b")

a:
[[0 1]
 [2 3]
 [4 5]]

b:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

a+b:
[[1. 2.]
 [3. 4.]
 [5. 6.]]

a-b:
[[-1.  0.]
 [ 1.  2.]
 [ 3.  4.]]

a*b:
[[0. 1.]
 [2. 3.]
 [4. 5.]]

a/b:
[[0. 1.]
 [2. 3.]
 [4. 5.]]



In [ ]:
# Unary operations
a = np.arange(6).reshape((3,2))
print_obj(a, "a")

print_obj(a.sum(), "a.sum()")
print_obj(a.sum(axis=0), "a.sum(axis=0)") #row-wise (axis=0) summation
print_obj(a.sum(axis=1), "a.sum(axis=1)") #col-wise (axis=0) summation

print_obj(a.mean(), "a.mean()")
print_obj(a.mean(axis=0), "a.mean(axis=0)")
print_obj(a.max(), "a.max()")
print_obj(a.min(), "a.min()")

# Quiz: Given a = np.arange(24).reshape((2,3,4)), what is the mean of the sum w.r.t to the last dimension?
a = np.arange(24).reshape((2,3,4))
print(a.sum(axis=-1).mean())

a:
[[0 1]
 [2 3]
 [4 5]]

a.sum():
15

a.sum(axis=0):
[6 9]

a.sum(axis=1):
[1 5 9]

a.mean():
2.5

a.mean(axis=0):
[2. 3.]

a.max():
5

a.min():
0

46.0


In [ ]:
# Vector dot product= np.dot(a,b)
a = np.arange(3).astype('float')
b = np.ones(3)
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.dot(a, b), "a dot b")


a:
[0. 1. 2.]

b:
[1. 1. 1.]

a dot b:
3.0



In [ ]:
# Matrix dot product, matrix multiplication
a = np.arange(6).reshape((3, 2))
b = np.ones((2, 3))
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.dot(a,b), "a dot b")
print_obj(a@b, "a @ b") # @(at) product = mat mult. operator (choose either .dot or @)

a:
[[0 1]
 [2 3]
 [4 5]]

b:
[[1. 1. 1.]
 [1. 1. 1.]]

a dot b:
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]

a @ b:
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]



In [ ]:
# Tensor dot product, tensor multiplication (diff from mat!!)

a = np.arange(24).reshape((4, 3, 2)) # 4 batches, 
b = np.ones((4, 2, 3)) # 4 batches, 
print_obj(a, "a")
print_obj(b, "b")

# first axis= (usually) batch

print_obj(np.dot(a,b).shape, "a dot b") # dot op: a's last dim = b's first dim, then deleted
#print(np.dot(a,b))

print_obj((a@b).shape, "a @ b") # @ op: if dim>3 parallel matching, if dim<=2 (matrix): matrix multiplication
print_obj(np.matmul(a, b).shape, "a @ b")
#print(a@b)

# Quiz: what would happen if a.shape==(4,3,2) and b.shape==(2,3)?
a = np.arange(24).reshape((4, 3, 2))
b = np.arange(6).reshape((2, 3))
print(np.dot(a,b)==a@b) # b is broad casted (a[0]*b, a[1]*b, ..., a[-1]*b)
print(a@b.shape)

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

b:
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]

a dot b:
(4, 3, 4, 3)

a @ b:
(4, 3, 3)

a @ b:
(4, 3, 3)

[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]
[[  3  13  23]
 [ 33  43  53]
 [ 63  73  83]
 [ 93 103 113]]


### Shape Manipulation

In [ ]:
# Reshapes
a = np.arange(24).reshape((2, 3, 4))
print_obj(a, "a")

b = a.reshape((6, 4))
print_obj(b, "b")

c = a.reshape((6, -1)) # -1= automatically calculated 4 u 
c = a.reshape((2,2, -1))
print_obj(c, "c")

# Quiz: What would d=a.reshape((6, 4, -1)) look like?
# A: all elem of b would be covered by []
d=a.reshape((6, 4, -1))
print(d)

a:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

b:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

c:
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]]

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]


In [ ]:
# Adding an extra dimension (often used): simply using None is clearly a timesaver
a = np.arange(3)
print_obj(a, "a")

print_obj(a[:, None], "a[:, None]")
print(a.reshape(3,1)) 

# Quiz: How to make a = np.ones((3,4)) into shape (3, 1, 1, 4) using reshape and None?
a = np.ones((3,4))
print(a.reshape(3,1,1,4).shape)
print(a[:, None, None,:].shape)
print(a[:, None, None].shape)

a:
[0 1 2]

a[:, None]:
[[0]
 [1]
 [2]]

[[0]
 [1]
 [2]]
(3, 1, 1, 4)
(3, 1, 1, 4)
(3, 1, 1, 4)


In [ ]:
# Stack, concatenation (often used)
a = np.ones((3,2))
b = np.zeros((3,2))
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.vstack([a, b]), "a,b vstack")
print_obj(np.hstack([a, b]), "a,b hstack")
print_obj(np.hstack([a, b, a]), "a,b,a hstack")

print_obj(np.concatenate([a, b], axis=0), "a,b concat axis=0") # axis=0 means row-wise concat= vstack
print_obj(np.concatenate([a, b], axis=1), "a,b concat axis=1") # axis=0 means col-wise concat= hstack

# Quiz: Would concatenating two tensors whose shapes are (4, 3, 2) and (5, 4, 2) on axis=2 work?
# A: No. 
a = np.ones((4,3,2))
b = np.zeros((4,3,4))
print(np.concatenate([a, b], axis=2))
print(np.concatenate([a, b], axis=1)) # remaining axe's dim should be same

a = np.ones((3,3,3))
b = np.zeros((3,3,2))
print(np.concatenate([a, b], axis=2))



a:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

b:
[[0. 0.]
 [0. 0.]
 [0. 0.]]

a,b vstack:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

a,b hstack:
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]

a,b,a hstack:
[[1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1.]]

a,b concat axis=0:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

a,b concat axis=1:
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]

[[[1. 1. 0. 0. 0. 0.]
  [1. 1. 0. 0. 0. 0.]
  [1. 1. 0. 0. 0. 0.]]

 [[1. 1. 0. 0. 0. 0.]
  [1. 1. 0. 0. 0. 0.]
  [1. 1. 0. 0. 0. 0.]]

 [[1. 1. 0. 0. 0. 0.]
  [1. 1. 0. 0. 0. 0.]
  [1. 1. 0. 0. 0. 0.]]

 [[1. 1. 0. 0. 0. 0.]
  [1. 1. 0. 0. 0. 0.]
  [1. 1. 0. 0. 0. 0.]]]


ValueError: ignored

In [ ]:
# Matrix transpose
a = np.arange(6).reshape((3, 2))
print_obj(a, "a")

print_obj(a.T, "a.T")

a:
[[0 1]
 [2 3]
 [4 5]]

a.T:
[[0 2 4]
 [1 3 5]]



In [ ]:
# Tensor transpose (swapping axis should be specified)
a = np.arange(24).reshape((4, 3, 2)) # 4 mini batches, 3 seqs, 2 samples in each seq
print_obj(a, "a")

b = np.transpose(a, [0, 2, 1]) # [0,1,2] => [0,2,1]
print_obj(b, "Swap axis 1 and 2")
print_obj(b.shape, "b's shape")

c = np.transpose(a, [1, 0, 2]) # sorted by seq order (not batch order= t)
print_obj(c, "Swap axis 0 and 1")
print_obj(c.shape, "c's shape")

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

Swap axis 1 and 2:
[[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]

 [[12 14 16]
  [13 15 17]]

 [[18 20 22]
  [19 21 23]]]

b's shape:
(4, 2, 3)

Swap axis 0 and 1:
[[[ 0  1]
  [ 6  7]
  [12 13]
  [18 19]]

 [[ 2  3]
  [ 8  9]
  [14 15]
  [20 21]]

 [[ 4  5]
  [10 11]
  [16 17]
  [22 23]]]

c's shape:
(3, 4, 2)



### Broadcasting

In [ ]:
# Vector and scalar
a = np.arange(3)
b = 2.
print_obj(a, "a")

# Scalar is broadcasted as if b=[2., 2., 2.]
print_obj(a+b, "a+b")
print_obj(a-b, "a-b")
print_obj(a*b, "a*b")
print_obj(a/b, "a/b")

# Comparison
b=np.array([2., 2., 2.])
print_obj(a+b, "a+b")
print_obj(a-b, "a-b")
print_obj(a*b, "a*b")
print_obj(a/b, "a/b")

a:
[0 1 2]

a+b:
[2. 3. 4.]

a-b:
[-2. -1.  0.]

a*b:
[0. 2. 4.]

a/b:
[0.  0.5 1. ]

a+b:
[2. 3. 4.]

a-b:
[-2. -1.  0.]

a*b:
[0. 2. 4.]

a/b:
[0.  0.5 1. ]



In [ ]:
# Matrix and vector
a = np.arange(6).reshape((3,2))
b = np.arange(2).reshape(2) + 1
print_obj(a, "a")
print_obj(b, "b")
print(b.shape) # the shape is internally set by (1,2) 

print_obj(a+b, "a+b")

# Quiz: What would happen if b were np.arange(2).reshape((2, 1))? How about np.arange(2).reshape((1, 2))?

np.arange(2).reshape((1, 2))
print_obj(a+b, "a+b")

b= np.arange(2).reshape((2, 1))
print_obj(a+b, "a+b")

a:
[[0 1]
 [2 3]
 [4 5]]

b:
[1 2]

(2,)
a+b:
[[1 3]
 [3 5]
 [5 7]]

a+b:
[[1 3]
 [3 5]
 [5 7]]



ValueError: ignored

In [ ]:
# Tensor and matrix
a = np.arange(12).reshape((2,3,2))
b = np.arange(6).reshape((3,2))
print_obj(a, "a")
print_obj(b, "b")

print_obj(a+b, "a+b")


#Quiz: How can we use None to do a+b?
print(b[None,:,:])
print(a+b[None,:,:])
print(a+b[None])

print(b[:,:,None])
print(b[None])

2
a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

b:
[[0 1]
 [2 3]
 [4 5]]

a+b:
[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[ 6  8]
  [10 12]
  [14 16]]]

[[[0 1]
  [2 3]
  [4 5]]]
[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[ 6  8]
  [10 12]
  [14 16]]]
[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[ 6  8]
  [10 12]
  [14 16]]]
[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]]
[[[0 1]
  [2 3]
  [4 5]]]


### Final Quiz

In [ ]:
import numpy as np

def sigmoid(x):
    return 1./(1. + np.exp(-x))

# Define a function that, given M of shape (m,n) and W of shape (4n, n), executes the following:
# - Take the first half rows of M
# - Take the second half rows of M
# - Take the odd-numbered rows of M
# - Take the even-numbered rows of M
# - Append them horizontally in the listed order so that you obtain a matrix X of shape (?, 4n): m/2
# - Linearly transform X with W so that you obtain a matrix Y of shape (?, ?): m/2, n (x*W case)
# - Put Y through the sigmoid function
# - Obtain the sum of the row-wise mean
def foo(M, W):
    m, n= M.shape
    fh=M[:M.shape[0]//2]
    sh=M[M.shape[0]//2:,:]
    
    idx=np.arange(m)
    on=M[idx%2==0]
    en=M[idx%2==1]

    x=np.concatenate([fh, sh, on, en], axis=1)
    Y=x@W
    temp=sigmoid(Y).mean(axis=0)
    
    return temp.sum()

def foo_ans(M, W):
    sh = M.shape
    a = M[:int(sh[0]/2)]
    b = M[int(sh[0]/2):]
    c = M[1:sh[0]:2]
    d = M[0:sh[0]:2]

    e = sigmoid(np.dot(np.concatenate([a, b, c, d], axis=1),W))
    #print(e)
    f = e.mean(axis=0)

    return np.sum(f)

M=np.array([[1,2],
            [3,4],
            [5,6],
            [7,8]])
W=np.array([[1,2],[3,4],[5,6],[7,8],[1,2],[3,4],[5,6],[7,8]])

print(foo_ans(M,W))
print(foo(M,W))


2.0
2.0
